export const ipDetailsTypes = {
    FETCH_IP_DETAILS_START : 'FETCH_IP_DETAILS_START',
    FETCH_IP_DETAILS_SUCCESS: 'FETCH_IP_DETAILS_SUCCESS',
    FETCH_IP_DETAILS_FIELIER: 'FETCH_IP_DETAILS_FIELIER'
}