export const weatherDetailsTypes = {
    WEATHER_DETAILS_START_FETCH : 'WEATHER_DETAILS_START_FETCH',
    WEATHER_DETAILS_FETCH_SUCCESS : 'WEATHER_DETAILS_FETCH_SUCCESS',
    WEATHER_DETAILS_FETCH_FILED : 'WEATHER_DETAILS_FETCH_FILED'
}